// Each new term in the Fibonacci sequence is generated by adding 
// the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not 
// exceed four million, find the sum of the even-valued terms.



// Notice that every third term after 2 is even, start sum at 2 and add every third
// term to sum
function fibAdder(max) {
	var first = 1,
		second = 2,
		third = 0,
		counter = 0;
		sum = 2;

	while(third < max) {
		third = first + second;
		first = second;
		second = third;
		counter++;
		if(counter === 3) {
			sum += third;
			counter = 0;
		}
	}
	return sum;
}

console.log(fibAdder(4000000));